CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;

DO $$ BEGIN
  CREATE TYPE run_status AS ENUM ('PENDING','VALIDATING','RUNNING','SUCCEEDED','FAILED','CANCELED');
EXCEPTION WHEN duplicate_object THEN null; END $$;
